### PR TITLE
oreo permission changes added

### PR DESCRIPTION
**Pull request by Rajeshtechgeek**
oreo permission changes added.

### CODE REVIEW

**Comment by JoaquimLey** [comment]
Thanks for the contribution, will look into this later today 👍 
- This is something I actually was to update soon, so your contribution is very welcome!

**Review by JoaquimLey — APPROVED** [review]
Awesome work, thanks for contributing ;)

**Comment by JoaquimLey** [comment]
Hi there @Rajeshtechgeek, so it looks like this was a _bug_ from Google?

I've now tested in a different app without that permission and I was able to use the `SmsManager`, can you check this SO question so maybe we can revert this?

- https://stackoverflow.com/q/46421412/3374428

**Comment by Rajeshtechgeek** [comment]
We don't need to revert this merge, As doc says clearly as below.

> Prior to Android 8.0 (API level 26), if an app requested a permission at runtime and the permission was granted, the system also incorrectly granted the app the rest of the permissions that belonged to the same permission group, and that were registered in the manifest.

> For apps targeting Android 8.0, this behavior has been corrected. The app is granted only the permissions it has explicitly requested. However, once the user grants a permission to the app, all subsequent requests for permissions in that permission group are automatically granted.

> For example, suppose an app lists both READ_EXTERNAL_STORAGE and WRITE_EXTERNAL_STORAGE in its manifest. The app requests READ_EXTERNAL_STORAGE and the user grants it. If the app targets API level 25 or lower, the system also grants WRITE_EXTERNAL_STORAGE at the same time, because it belongs to the same STORAGE permission group and is also registered in the manifest. If the app targets Android 8.0 (API level 26), the system grants only READ_EXTERNAL_STORAGE at that time; however, if the app later requests WRITE_EXTERNAL_STORAGE, the system immediately grants that privilege without prompting the user.

I don't think this is a bug from google.

**Comment by JoaquimLey** [comment]
Hi there @Rajeshtechgeek,

Thanks for providing the info. Maybe I didn't explain myself correctly, what I meant is, we don't actually need the ` READ_PHONE_STATE`permission anymore when calling `SmsManager.sendTextMessage()`.

I've been using the `SMS` feature on another project

- [joaquimley/transport-eta](https://github.com/JoaquimLey/transport-eta)

You can check the `develop` or `feature/favorite_list` branches of this project and test. The only permissions I'm requesting now are as follows:

```xml
<uses-permission android:name="android.permission.RECEIVE_SMS" />
<uses-permission android:name="android.permission.READ_SMS" />
<uses-permission android:name="android.permission.SEND_SMS" />
```
And it is working perfectly, can you please try on your end?
I've tested from `API 19` all the way to  `27`.

**Comment by Rajeshtechgeek** [comment]
Yes, we don't actually need the READ_PHONE_STATE permission anymore when calling SmsManager.sendTextMessage().

**Comment by JoaquimLey** [comment]
Would you like to do a PR that undoes this or should I? 😃

**Comment by Rajeshtechgeek** [comment]
I think we don't have READ_PHONE_STATE permission in this app right?.

**Comment by JoaquimLey** [comment]
You're right, sorry for the confusion 🤦‍♂️

**Pull request merged**
