### PR TITLE
Re-upated SmsBroadcastReceiver.java :)

### PR DESCRIPTION
**Pull request by seckalou**

### CODE REVIEW

**Comment by JoaquimLey** [comment]
Hey there, thanks for your contribution.

Can you explain what you are trying to achieve with this change?

**Comment by seckalou** [comment]
Hi,
Just trying to make it work. Looked at you blog and noticed it didn't match the srcs here.

**Comment by JoaquimLey** [comment]
Can you give me the examples on the blog that do not work? 
This has a lot of changes that don't look required, do you agree?

**Comment by JoaquimLey** [comment]
I liked the way you passed the conditionals through the constructor, making the broadcast receiver more reusable.

Closing due to staleness and lack of answer(s) from the contributor.

**Pull request closed without merging**
